name: Build Android APK (Debug)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:stable
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Buildozer/Gradle/Android
        uses: actions/cache@v4
        with:
          path: |
            ~/.buildozer
            ~/.gradle/caches
            ~/.android
          key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            buildozer-${{ runner.os }}-

      - name: Show versions
        run: |
          python --version || true
          buildozer --version || true

      - name: Build Debug APK
        run: |
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: marble-granite-debug-apk
          path: bin/*.apk
          if-no-files-found: error
